# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

# Build the project
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'
    projects: 'src/FluentAssertions.CSharpFunctionalExtensions/FluentAssertions.CSharpFunctionalExtensions.csproj'

# Run tests
- task: DotNetCoreCLI@2
  displayName: 'run tests'
  inputs:
    command: test
    projects: '**/*Spec/*.csproj'
    arguments: '--configuration $(buildConfiguration)'